version: '3.6'

networks:
  boilerplate:
    name: boilerplate

services:
  db:
    image: keinos/sqlite3:latest
    container_name: db
    hostname: db
    networks:
      - boilerplate
    volumes:
      - .sqlite/:/root/db/
    environment:
      TZ: UTC
    restart: unless-stopped
    tty: true

  node:
    container_name: node
    hostname: node
    working_dir: /usr/src/app
    build:
      context: .
      target: dev-attached
      args:
        USER_GID: 1001
        USER_UID: 1001
    cap_add:
      - SYS_ADMIN
    networks:
      - boilerplate
    ports:
      - ${APP_PORT}:4200
      - ${API_PORT}:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: UTC
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    depends_on:
      - db
    restart: unless-stopped
    stdin_open: true
    tty: true
