version: '3.6'

networks:
  boilerplate:
    name: boilerplate

services:
  node:
    container_name: node
    hostname: node
    working_dir: /usr/src/app
    build:
      context: .
      target: dev-attached
      args:
        USER_GID: 1001
        USER_UID: 1001
    cap_add:
      - SYS_ADMIN
    networks:
      - boilerplate
    ports:
      - ${APP_PORT}:4200
      - ${API_PORT}:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: UTC
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      MIKRO_ORM_CLI: src/database/mikro-orm.config.ts
      MIKRO_ORM_CLI_TS_CONFIG_PATH: tsconfig.json
      MIKRO_ORM_CLI_USE_TS_NODE: 1
    restart: unless-stopped
    stdin_open: true
    tty: true
